add mern stack functionality

diff --git a/chajr b/chajr
--- a/chajr
+++ b/chajr
@@ -2,7 +2,7 @@
 # Welcome to chajr - Css Html And Javascript Ready - A script by David Stinson.
 # This script builds a simple local environment to develop JS, HTML, and CSS.
 # It can also build a starter environment to develop Node applications using 
-# MongoDB and Express. 
+# MongoDB and Express or build a MERN stack application.
 # Let's all stop wasting time setting up file structures!
 
 NEWDIR=""
@@ -13,6 +13,7 @@ BLANK=""
 EDITOR=""
 LOCAL=""
 MEN=""
+MERN=""
 PRETTIER=""
 REMOTE=""
 REMOTEADDRESS=""
@@ -23,11 +24,12 @@ function main(){
 
 function check_options(){
   local OPTIND opt i
-  while getopts ":belnpr:v" opt; do
+  while getopts ":belmnpr:v" opt; do
     case $opt in
       b)  BLANK=True;;
       e)  EDITOR=True;;
       l)  LOCAL=True;;
+      m)  MERN=True;;
       n)  MEN=True;;
       p)  PRETTIER=True;;
       r)
@@ -35,10 +37,10 @@ function check_options(){
           REMOTEADDRESS="$OPTARG"
           ;;
       v)
-          echo "Version 1.1.4"
+          echo "Version 1.2"
           echo "New in this version:"
-          echo "  - Fix for erroneous mkdir directory being created in"
-          echo "    working directory"
+          echo "  - Add -m option to create a project with a"
+          echo "    MERN stack"
           echo " "
           echo "Give feedback on this version at:"
           echo "https://github.com/DavidStinson/chajr/issues"
@@ -47,8 +49,14 @@ function check_options(){
     esac
   done
   shift $((OPTIND -1))
-  NEWDIR="$1"
-  NEWDIRPATH="$WD""/""$1"
+
+  if [ "$MERN" == True ]; then
+    NEWDIR=$( echo "$1" | tr '[:upper:]' '[:lower:]' )
+    NEWDIRPATH="$WD""/""$NEWDIR"
+  else
+    NEWDIR="$1"
+    NEWDIRPATH="$WD""/""$NEWDIR"
+  fi
 
   check_for_input_errors
 }
@@ -73,6 +81,28 @@ function check_for_input_errors(){
     help; exit 1
   fi
 
+  if [ "$MERN" == True ] && [ "$BLANK" == True ]; then
+    echo " "
+    echo "*WARNING!* A README.md only chajr and a MERN chajr"
+    echo "cannot be created simultaneously. Pick 1 option, then try again."
+    echo " "
+    echo "*CRITICAL FAILURE!* chajr NOT built in the ""$NEWDIR"" directory due"
+    echo "to file structure option conflict."
+    echo " "
+    help; exit 1
+  fi
+
+  if [ "$MERN" == True ] && [ "$MEN" == True ]; then
+    echo " "
+    echo "*WARNING!* MEN and MERN stack may not be used"
+    echo "simultaneously. Pick 1 option, then try again."
+    echo " "
+    echo "*CRITICAL FAILURE!* chajr NOT built in the ""$NEWDIR"" directory due"
+    echo "to a stack option conflict."
+    echo " "
+    help; exit 1
+  fi
+
   if [ "$REMOTE" == True ] && [ "$LOCAL" == True ]; then
     echo " "
     echo "*WARNING!* Remote and local repository setup may not be used"
@@ -84,7 +114,7 @@ function check_for_input_errors(){
     githelp; exit 1
   fi
 
-  if [ "$REMOTEADDRESS" == " " ] || [ "$REMOTEADDRESS" == "-b" ] || [ "$REMOTEADDRESS" == "b" ] || [ "$REMOTEADDRESS" == "-e" ] || [ "$REMOTEADDRESS" == "e" ] || [ "$REMOTEADDRESS" == "-l" ] || [ "$REMOTEADDRESS" == "l" ] || [ "$REMOTEADDRESS" == "-n" ] || [ "$REMOTEADDRESS" == "n" ] || [ "$REMOTEADDRESS" == "-p" ] || [ "$REMOTEADDRESS" == "p" ] || [ "$REMOTEADDRESS" == "-r" ] || [ "$REMOTEADDRESS" == "r" ] || [ "$REMOTEADDRESS" == "-v" ] || [ "$REMOTEADDRESS" == "v" ]; then
+  if [ "$REMOTEADDRESS" == " " ] || [ "$REMOTEADDRESS" == "-b" ] || [ "$REMOTEADDRESS" == "b" ] || [ "$REMOTEADDRESS" == "-e" ] || [ "$REMOTEADDRESS" == "e" ] || [ "$REMOTEADDRESS" == "-l" ] || [ "$REMOTEADDRESS" == "l" ] || [ "$REMOTEADDRESS" == "-m" ] || [ "$REMOTEADDRESS" == "m" ] || [ "$REMOTEADDRESS" == "-n" ] || [ "$REMOTEADDRESS" == "n" ] || [ "$REMOTEADDRESS" == "-p" ] || [ "$REMOTEADDRESS" == "p" ] || [ "$REMOTEADDRESS" == "-r" ] || [ "$REMOTEADDRESS" == "r" ] || [ "$REMOTEADDRESS" == "-v" ] || [ "$REMOTEADDRESS" == "v" ]; then
       echo " "
       echo "*WARNING!* No remote repository address provided!"
       echo " "
@@ -92,7 +122,7 @@ function check_for_input_errors(){
       echo "The -r option must have a remote address after it."
       echo " "
       githelp; exit 1
-  fi 
+  fi
 
   build
 }
@@ -102,12 +132,15 @@ function build(){
   # If manually installing, replace the text between cat and >> with a full
   # path to your template files, surrounded by quotes. Repeat for each 
   # template file.
-  echo "# ""$NEWDIR" >> "$NEWDIR""/"README.md
-  echo "#### Started on: $(date '+%m-%d-%Y')" >> "$NEWDIR""/"README.md
-  cat  "$BREW""/etc/chajr/readmeTemplate.txt">> "$NEWDIR""/"README.md
+
+  if [ "$MERN" != True ]
+    echo "# ""$NEWDIR" >> "$NEWDIR""/"README.md
+    echo "#### Started on: $(date '+%m-%d-%Y')" >> "$NEWDIR""/"README.md
+    cat  "$BREW""/etc/chajr/readmeTemplate.txt">> "$NEWDIR""/"README.md
+  fi
 
   if [ "$BLANK" != True ]; then
-    if [ "$MEN" != True ]; then
+    if [ "$MEN" != True ] && [ "$MERN" != True ]; then
       mkdir "$NEWDIR""/"css "$NEWDIR""/"js "$NEWDIR""/"images
       cat "$BREW""/etc/chajr/htmlTemplate.txt" >> "$NEWDIR""/"index.html
       cat "$BREW""/etc/chajr/cssTemplate.txt" >> "$NEWDIR""/"css/main.css
@@ -134,6 +167,9 @@ function build(){
       cat "$BREW""/etc/chajr/node/views/viewsErrorTemplate.txt" >> "$NEWDIR""/"views/error.ejs
       cat "$BREW""/etc/chajr/node/packageJsonTemplate.txt" >> "$NEWDIR""/"package.json
     fi
+    if [ "$MERN" == True ]; then
+      npx create-react-app "$NEWDIR"
+    fi
   fi
   if [ "$PRETTIER" == True ]; then
     cat "$BREW""/etc/chajr/prettierTemplate.txt" >> "$NEWDIR""/".prettierrc
@@ -159,18 +195,91 @@ function check_build_success(){
 
 function post_build_processes(){
   cd "$NEWDIRPATH"
-  if [ "$REMOTE" == True ]; then
-    git init
-    git add .
-    git commit -m "first commit"
-    git remote add origin "$REMOTEADDRESS"
-    git push -u origin master
+  if [ "$MERN" == True ]; then
+    npm i express morgan serve-favicon mongoose react-router-dom dotenv
+    cd ..
+    mkdir "$NEWDIR""/"config
+    mkdir "$NEWDIR""/"controllers 
+    mkdir "$NEWDIR""/"models 
+    mkdir "$NEWDIR""/"routes
+    mkdir "$NEWDIR""/"routes/api 
+    mkdir "$NEWDIR""/"src/pages 
+    mkdir "$NEWDIR""/"src/pages/App
+    mkdir "$NEWDIR""/"src/pages/Login
+    mkdir "$NEWDIR""/"src/pages/Signup
+    mkdir "$NEWDIR""/"src/pages/TktksSecretPage
+    mkdir "$NEWDIR""/"src/components
+    mkdir "$NEWDIR""/"src/components/NavBar
+    mkdir "$NEWDIR""/"src/components/SignupForm
+    mkdir "$NEWDIR""/"src/components/Tktk
+    mkdir "$NEWDIR""/"src/services/
+
+    cat "$BREW""/etc/chajr/mern/serverTemplate.txt" >> "$NEWDIR""/"server.js
+    cat "$BREW""/etc/chajr/mern/procfileTemplate.txt" >> "$NEWDIR""/"Procfile
+    cat "$BREW""/etc/chajr/mern/envTemplate.txt" >> "$NEWDIR""/".env
+    cat "$BREW""/etc/chajr/mern/routes/apiTktksTemplate.txt" >> "$NEWDIR""/"routes/api/tktks.js
+    cat "$BREW""/etc/chajr/mern/routes/apiUsersTemplate.txt" >> "$NEWDIR""/"routes/api/users.js
+    cat "$BREW""/etc/chajr/mern/config/dbTemplate.txt" >> "$NEWDIR""/"config/database.js
+    cat "$BREW""/etc/chajr/mern/config/authTemplate.txt" >> "$NEWDIR""/"config/auth.js
+    cat "$BREW""/etc/chajr/mern/models/tktkTemplate.txt" >> "$NEWDIR""/"models/tktk.js
+    cat "$BREW""/etc/chajr/mern/models/userTemplate.txt" >> "$NEWDIR""/"models/user.js
+    cat "$BREW""/etc/chajr/mern/controllers/tktksTemplate.txt" >> "$NEWDIR""/"controllers/tktks.js
+    cat "$BREW""/etc/chajr/mern/controllers/usersTemplate.txt" >> "$NEWDIR""/"controllers/users.js
+    cat "$BREW""/etc/chajr/mern/pages/indexTemplate.txt" > "$NEWDIR""/"src/index.js
+    cat "$BREW""/etc/chajr/mern/pages/appTemplate.txt" >> "$NEWDIR""/"src/pages/App/App.js
+    cat "$BREW""/etc/chajr/mern/pages/appCssTemplate.txt" >> "$NEWDIR""/"src/pages/App/App.css
+    cat "$BREW""/etc/chajr/mern/pages/loginTemplate.txt" >> "$NEWDIR""/"src/pages/LoginPage/LoginPage.jsx
+    cat "$BREW""/etc/chajr/mern/pages/loginCssTemplate.txt" >> "$NEWDIR""/"src/pages/LoginPage/LoginPage.css
+    cat "$BREW""/etc/chajr/mern/pages/signupTemplate.txt" >> "$NEWDIR""/"src/pages/SignupPage/SignupPage.jsx
+    cat "$BREW""/etc/chajr/mern/pages/signupCssTemplate.txt" >> "$NEWDIR""/"src/pages/SignupPage/SignupPage.css
+    cat "$BREW""/etc/chajr/mern/pages/tktkSecretTemplate.txt" >> "$NEWDIR""/"src/pages/TktksSecretPage/TktksSecretPage.jsx
+    cat "$BREW""/etc/chajr/mern/components/NavBarTemplate.txt" >> "$NEWDIR""/"src/components/NavBar/NavBar.jsx
+    cat "$BREW""/etc/chajr/mern/components/NavBarCssTemplate.txt" >> "$NEWDIR""/"src/components/NavBar/NavBar.css
+    cat "$BREW""/etc/chajr/mern/components/SigupFormTemplate.txt" >> "$NEWDIR""/"src/components/SignupForm/SignupForm.jsx
+    cat "$BREW""/etc/chajr/mern/components/TktkTemplate.txt" >> "$NEWDIR""/"src/components/Tktk/Tktk.jsx
+    cat "$BREW""/etc/chajr/mern/services/tktkApiTemplate.txt" >> "$NEWDIR""/"src/services/tktk-api.js
+    cat "$BREW""/etc/chajr/mern/services/userApiTemplate.txt" >> "$NEWDIR""/"src/services/user-api.js
+    cat "$BREW""/etc/chajr/mern/services/tokenTemplate.txt" >> "$NEWDIR""/"src/services/tokenService.js
+
+
+    rm "$NEWDIR"/src/App.js
+    rm "$NEWDIR"/src/App.css
+    rm "$NEWDIR"/src/App.test.js
+    rm "$NEWDIR"/src/setupTests.js
+    rm "$NEWDIR"/src/logo.svg
+
+    sed -i '' '$d' "$NEWDIR""/"package.json
+    sed -i '' '$d' "$NEWDIR""/"package.json
+    cat "$BREW""/etc/chajr/mern/packageJsonExtension.txt" >> "$NEWDIR""/"package.json
+
+    echo "# ""$NEWDIR" >> "$NEWDIR""/"README.md
+    echo "#### Started on: $(date '+%m-%d-%Y')" >> "$NEWDIR""/"README.md
+    cat  "$BREW""/etc/chajr/readmeTemplate.txt">> "$NEWDIR""/"README.md
+
+    npm run build
+
+    if [ "$REMOTE" == True ]; then
+      cd "$NEWDIRPATH"
+      git add .
+      git commit -m "first commit"
+      git remote add origin "$REMOTEADDRESS"
+      git push -u origin master
+    fi
+  else
+    if [ "$REMOTE" == True ]; then
+      git init
+      git add .
+      git commit -m "first commit"
+      git remote add origin "$REMOTEADDRESS"
+      git push -u origin master
+    fi
+    if [ "$LOCAL" == True ]; then
+      git init
+      git add .
+      git commit -m "first commit"
+    fi
   fi
-  if [ "$LOCAL" == True ]; then
-    git init
-    git add .
-    git commit -m "first commit"
-  fi
+  
   # init npm AFTER adding remotes to include remotes in package.json
   if [ "$MEN" == True ]; then
     npm init --yes
@@ -187,7 +296,7 @@ function post_build_processes(){
 
 function help(){
   echo " "
-  echo "Usage: chajr [-e] [-h] [-p] [-v] [-b | -n ]"
+  echo "Usage: chajr [-e] [-h] [-p] [-v] [-b | -m | -n ]"
   echo "             [-l | -r <remote-repository-path>]"
   echo "             <dirtocreate>"
   echo " "
@@ -195,7 +304,7 @@ function help(){
   echo " "
   echo "  -b"
   echo "      Creates the directory specified with only a README.md file"
-  echo "      inside of it. Cannot be used with the -n option."
+  echo "      inside of it. Cannot be used with the -m or -n option."
   echo " "
   echo "  -e"
   echo "      Opens the new directory in Visual Studio Code."
@@ -208,9 +317,13 @@ function help(){
   echo "      local git repository inside the new directory, and makes an"
   echo "      initial commit."
   echo " "
+  echo "  -m"
+  echo "      Builds a MERN (MongoDB, Express, React, and Node.js) stack"
+  echo "      chajr. Cannot be used with the -b or -n option"
+  echo " "
   echo "  -n"
   echo "      Builds a Node.js, Express, and MongoDB ready chajr. Cannot be"
-  echo "      used with the -b option"
+  echo "      used with the -b or the -m option"
   echo " "
   echo "  -p"
   echo "      Adds a .prettierrc configuration file in the project directory."
